name: Gas
channels:
  - conda-forge
  - anaconda-fusion
  - defaults
dependencies:
  - python=3.8
  - jupyterlab
  - pandas
  - numpy
  - seaborn
  - matplotlib
  - ipykernel
  - lxml
  - html5lib
  - beautifulsoup4
  - tabulate
  - pip
  - pip:
      - ipypb
