name: Update data

on: push

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
        
    - name: Install packages and run update
      run: |
        dir
        python -m pip install --upgrade pip
        pip install tabulate pandas io json requests
        python update_data.py
      
    - uses: stefanzweifel/git-auto-commit-action@v4
